yumroad/blueprints/landing.py
from sqlalchemy.orm import joinedload
from flask import Blueprint, render_template
from flask_login import current_user
from yumroad.models import Store
from yumroad.extensions import cache

landing_bp = Blueprint('landing', __name__)

@landing_bp.route('/')
@cache.cached(timeout=120, unless=lambda: current_user.is_authenticated)
def index():
    # This is a bad query, optimize it later
    stores = Store.query.options(
        joinedload(Store.products)
    ).limit(3).all()
    return render_template('landing/index.html', stores=stores)

yumroad/blueprints/users.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request

from yumroad.extensions import db, login_manager
from yumroad.models import User, Store
from yumroad.forms import SignupForm, LoginForm
from yumroad.email import send_welcome_message

from flask_login import login_user, current_user, login_required, logout_user

user_bp = Blueprint('user', __name__)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

@login_manager.unauthorized_handler
def unauthorized():
    session['after_login'] = request.url
    flash('You need to login', 'warning')
    return redirect(url_for('user.login'))

@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash('You are already logged in', 'warning')
        return redirect(url_for('products.index'))
    form = SignupForm()
    if form.validate_on_submit():
        # create a user
        user = User.create(form.email.data, form.password.data)
        db.session.add(user)
        store = Store(name=form.store_name.data, user=user)  # may need another db.session.add(store)
        db.session.commit()
        login_user(user)
        send_welcome_message(user)
        flash("Registered successfully", "success")
        return redirect(url_for('products.index'))
    return render_template('users/register.html', form=form)

@user_bp.route('/login', methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:
        flash('You are already logged in', 'warning')
        return redirect(url_for('products.index'))

    form = LoginForm()
    if form.validate_on_submit():
        # log in user
        user = User.query.filter_by(email=form.email.data).one()
        login_user(user)
        flash('Logged in successfully', 'success')
        return redirect(session.get('after_login') or url_for('products.index'))
    return render_template('users/login.html', form=form)

@user_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('products.index'))

yumroad/templates/_formhelpers.html
{% macro render_field(field) %}
    <div class="form-group {% if field.errors %} has-error{% endif -%} {%- if field.flags.required %} required{% endif -%}">
        <label for="{{ field.name }}">{{ field.label }}</label>
        {% if field.description %}
            <small classname="text_muted" for="{{ field.name }}">({{ field.description }})</small>
        {% endif %}
        {{ field(class_=' '.join(['form-control', 'is-invalid' if field.errors else '']), **kwargs)|safe }}
        <ul class="invalid-feedback errors">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endmacro %}

yumroad/templates/_macros.html
{% macro render_flashes() %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="container mt-4">
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        </button>
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
{% endmacro %}

yumroad/templates/base_layout.html
{% from "_macros.html" import render_flashes %}

<html>
    <head>
        <title>{% block title %}{% endblock %} | Yumroad</title>

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% assets "common_css" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
        {% endassets %}

        {% assets "common_js" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}

        {% block custom_assets %}

        {% endblock %}

        <meta name="csrf_token" content="{{ csrf_token() }}">
    
    </head>
    <body>
        <nav class="navbar navbar-light bg-light justify-content-between">
            <a href="{{ url_for('landing.index') }}" class="navbar-brand">Yumroad</a>
            <div class="navbar-item form-inline">
                {% if current_user.is_authenticated %}
                    <a class="ml-3 navbar-link">{{ current_user.email }}</a>
                    <a class="nav-link" href="{{ url_for('user.logout') }}">Log out</a>
                {% else %}
                    <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
                    <a class="nav-link" href="{{ url_for('user.register') }}">Register</a>
                {% endif %}
            </div>
        </nav>
        {{ render_flashes() }}
        <div class="container mt-3">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>